<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\User;
use App\Models\UserCourse;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $trainer = User::where('email', 'trainer01@test.com')->first();

        $courses = [
            // --- Existing courses ---
            ['title' => 'CyberSAFE® for Citizens', 'description' => 'A foundational course covering basic cybersecurity awareness. Participants will learn to identify common online threats like phishing, understand the importance of strong passwords, and manage digital risks to protect sensitive information.', 'url' => 'https://rakyatdigital.gov.my/courses/cybersafe-untuk-rakyat', 'level' => 'beginner', 'title_bm' => 'CyberSAFE® untuk Rakyat', 'description_bm' => 'Kursus asas yang merangkumi kesedaran keselamatan siber asas. Peserta akan belajar mengenal pasti ancaman dalam talian yang biasa seperti pancingan data, memahami kepentingan kata laluan yang kukuh, dan menguruskan risiko digital untuk melindungi maklumat sensitif.', 'image' => 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800&q=80'],
            ['title' => 'AI for Citizens', 'description' => 'A short introductory program designed to demystify Artificial Intelligence. It explains the basics of AI and its application in daily life, concluding with a certificate of completion.', 'url' => 'https://rakyatdigital.gov.my/courses/ai-untuk-rakyat', 'level' => 'beginner', 'title_bm' => 'AI untuk Rakyat', 'description_bm' => 'Program pengenalan ringkas yang direka untuk menjelaskan Kecerdasan Buatan. Ia menerangkan asas AI serta aplikasinya dalam kehidupan seharian, diakhiri dengan sijil penyiapan.', 'image' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80'],
            ['title' => 'Cloud for Citizens', 'description' => 'An introductory module on cloud computing principles. This course explains how cloud services can be used to enhance productivity, enable data storage, and facilitate collaboration among teams.', 'url' => 'https://rakyatdigital.gov.my', 'level' => 'beginner', 'title_bm' => 'Pengkomputeran Awan untuk Rakyat', 'description_bm' => 'Modul pengenalan tentang prinsip pengkomputeran awan. Kursus ini menerangkan bagaimana perkhidmatan awan boleh digunakan untuk meningkatkan produktiviti, membolehkan penyimpanan data, dan memudahkan kerjasama dalam kalangan pasukan.', 'image' => 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&q=80'],
            ['title' => 'Basic Microsoft Word for Government Use', 'description' => 'Learn essential Microsoft Word skills tailored for government administrative work. Covers document formatting, templates, mail merge, and collaborative editing features.', 'level' => 'beginner', 'title_bm' => 'Microsoft Word Asas untuk Kegunaan Kerajaan', 'description_bm' => 'Pelajari kemahiran Microsoft Word penting yang disesuaikan untuk kerja pentadbiran kerajaan.', 'image' => 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80'],
            ['title' => 'Google Workspace Essentials', 'description' => 'Master the core Google Workspace tools including Gmail, Google Drive, Docs, Sheets, and Meet for improved productivity and collaboration.', 'level' => 'beginner', 'title_bm' => 'Penting Google Workspace', 'description_bm' => 'Kuasai alat Google Workspace teras termasuk Gmail, Google Drive, Docs, Sheets, dan Meet.', 'image' => 'https://images.unsplash.com/photo-1512756290469-ec264b7fbf87?w=800&q=80'],
            ['title' => 'Canva Design for Beginners', 'description' => 'Learn to create professional-looking presentations, social media graphics, and documents using Canva. No design experience required.', 'level' => 'beginner', 'title_bm' => 'Rekaan Canva untuk Pemula', 'description_bm' => 'Belajar mencipta persembahan profesional menggunakan Canva.', 'image' => 'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=800&q=80'],
            ['title' => 'Digital Government & E-Services', 'description' => 'Understand Malaysia\'s digital government initiatives and learn to navigate e-services platforms effectively for both personal and professional use.', 'level' => 'beginner', 'title_bm' => 'Kerajaan Digital & E-Perkhidmatan', 'description_bm' => 'Fahami inisiatif kerajaan digital Malaysia.', 'image' => 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&q=80'],
            ['title' => 'Introduction to Data Literacy', 'description' => 'Develop foundational skills in reading, understanding, and communicating with data. Learn to interpret charts, graphs, and basic statistics.', 'level' => 'beginner', 'title_bm' => 'Pengenalan Literasi Data', 'description_bm' => 'Kembangkan kemahiran asas dalam membaca dan memahami data.', 'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80'],

            // --- C1 – Digital Literacy ---
            ['title' => 'Global Digital Literacy', 'description' => 'Learn how to safely and effectively navigate the digital world. This course covers internet research, online collaboration, digital communication, and content creation fundamentals for learners of all backgrounds.', 'url' => 'https://alison.com/course/global-digital-literacy', 'level' => 'beginner', 'title_bm' => 'Literasi Digital Global', 'description_bm' => 'Belajar cara menyelami dunia digital dengan selamat dan berkesan. Kursus ini merangkumi penyelidikan internet, kerjasama dalam talian, komunikasi digital, dan asas penciptaan kandungan.', 'image' => 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80'],
            ['title' => 'Information Literacy in the Digital Age', 'description' => 'Develop the ability to identify misinformation and fake news, verify digital content, and strengthen media literacy skills essential for navigating today\'s information landscape.', 'url' => 'https://alison.com/course/information-integrity-and-media-literacy', 'level' => 'intermediate', 'title_bm' => 'Literasi Maklumat dalam Era Digital', 'description_bm' => 'Kembangkan keupayaan untuk mengenal pasti maklumat palsu dan berita palsu, mengesahkan kandungan digital, dan mengukuhkan kemahiran literasi media.', 'image' => 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&q=80'],
            ['title' => 'Emerging Technologies for Government', 'description' => 'Explore how emerging technologies such as blockchain, Internet of Things (IoT), and artificial intelligence are shaping the future of public sector services and governance.', 'url' => 'https://rakyatdigital.gov.my/', 'level' => 'advanced', 'title_bm' => 'Teknologi Membangunku untuk Kerajaan', 'description_bm' => 'Teroka bagaimana teknologi membangu seperti rantaian blok, Internet of Things (IoT), dan kecerdasan buatan membentuk masa depan perkhidmatan sektor awam dan tadbir urus.', 'image' => 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=800&q=80'],

            // --- C2 – Digital Skills ---
            ['title' => 'IT Fundamentals for Beginners', 'description' => 'Build essential IT skills including using devices, browsing the internet, managing emails, and staying safe online. Suitable for those new to digital technology.', 'url' => 'https://alison.com/course/it-fundamentals-for-beginners', 'level' => 'beginner', 'title_bm' => 'Asas IT untuk Pemula', 'description_bm' => 'Bina kemahiran IT penting termasuk penggunaan peranti, melayari internet, mengurus e-mel, dan kekal selamat dalam talian.', 'image' => 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80'],
            ['title' => 'Work Smarter with Microsoft Excel', 'description' => 'Learn how to create spreadsheets, work with formulas and functions, format data professionally, and produce charts and pivot tables for data analysis.', 'url' => 'https://www.coursera.org/learn/microsoft-excel-work-smarter', 'level' => 'intermediate', 'title_bm' => 'Bekerja Lebih Bijak dengan Microsoft Excel', 'description_bm' => 'Pelajari cara mencipta hamparan, bekerja dengan formula dan fungsi, memformat data secara profesional, dan menghasilkan carta serta jadual pangsi.', 'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80'],
            ['title' => 'Microsoft Power Platform Fundamentals', 'description' => 'Learn the business value and product capabilities of Microsoft Power Platform. Create simple Power Apps, connect data with Dataverse, build Power BI dashboards, and automate workflows with Power Automate.', 'url' => 'https://learn.microsoft.com/en-us/training/paths/power-plat-fundamentals/', 'level' => 'advanced', 'title_bm' => 'Asas Platform Kuasa Microsoft', 'description_bm' => 'Pelajari nilai perniagaan dan keupayaan produk Platform Kuasa Microsoft. Cipta Power Apps ringkas, sambung data dengan Dataverse, bina papan pemuka Power BI.', 'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80'],

            // --- C3 – Communication & Collaboration ---
            ['title' => 'Professional Email and Online Communication', 'description' => 'Master professional email writing, online meeting etiquette, and digital communication best practices for workplace effectiveness and collaboration.', 'url' => 'https://learn.microsoft.com/en-us/training/', 'level' => 'beginner', 'title_bm' => 'E-mel Profesional dan Komunikasi Dalam Talian', 'description_bm' => 'Kuasai penulisan e-mel profesional, etika mesyuarat dalam talian, dan amalan terbaik komunikasi digital untuk keberkesanan tempat kerja.', 'image' => 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=800&q=80'],
            ['title' => 'Collaborate with Microsoft Teams', 'description' => 'Learn to use Microsoft Teams effectively for team communication, file sharing, channel management, online meetings, and collaborative project work.', 'url' => 'https://learn.microsoft.com/en-us/training/teams/', 'level' => 'intermediate', 'title_bm' => 'Bekerjasama dengan Microsoft Teams', 'description_bm' => 'Pelajari cara menggunakan Microsoft Teams dengan berkesan untuk komunikasi pasukan, perkongsian fail, pengurusan saluran, dan kerja projek kolaboratif.', 'image' => 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80'],
            ['title' => 'Stakeholder Engagement in Digital Projects', 'description' => 'Learn strategies for effective stakeholder identification, communication planning, and engagement techniques specifically for digital transformation projects.', 'url' => 'https://www.coursera.org/learn/effective-stakeholder-management', 'level' => 'advanced', 'title_bm' => 'Penglibatan Pihak Berkepentingan dalam Projek Digital', 'description_bm' => 'Pelajari strategi untuk pengenalpastian pihak berkepentingan, perancangan komunikasi, dan teknik penglibatan khusus untuk projek transformasi digital.', 'image' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80'],

            // --- C4 – Problem-Solving & Critical Thinking ---
            ['title' => 'Critical Thinking and Decision Making', 'description' => 'Develop structured analytical thinking skills for better decision making. Learn to evaluate arguments, identify logical fallacies, and apply critical reasoning to workplace challenges.', 'url' => 'https://alison.com/course/critical-thinking', 'level' => 'beginner', 'title_bm' => 'Pemikiran Kritikal dan Membuat Keputusan', 'description_bm' => 'Kembangkan kemahiran pemikiran analitik berstruktur untuk membuat keputusan yang lebih baik. Pelajari cara menilai hujah dan mengenal pasti kesilapan logik.', 'image' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80'],
            ['title' => 'Data-Driven Problem Solving', 'description' => 'Learn to leverage data analytics to identify problems, measure outcomes, and make evidence-based decisions. Covers data collection, analysis techniques, and presenting findings.', 'url' => 'https://www.coursera.org/learn/data-driven-decision-making', 'level' => 'intermediate', 'title_bm' => 'Penyelesaian Masalah Berdasarkan Data', 'description_bm' => 'Pelajari cara menggunakan analitik data untuk mengenal pasti masalah, mengukur hasil, dan membuat keputusan berasaskan bukti.', 'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80'],
            ['title' => 'Design Thinking for Public Services', 'description' => 'Apply human-centered design thinking methodology to innovate and improve public services. Learn to empathize with users, define problems, ideate solutions, prototype, and test.', 'url' => 'https://www.coursera.org/learn/design-thinking-for-innovation', 'level' => 'advanced', 'title_bm' => 'Pemikiran Reka Bentuk untuk Perkhidmatan Awam', 'description_bm' => 'Gunakan metodologi pemikiran reka bentuk berpusatkan manusia untuk berinovasi dan menambah baik perkhidmatan awam.', 'image' => 'https://images.unsplash.com/photo-1531498860502-7c67cf02f657?w=800&q=80'],

            // --- C5 – Digital Safety & Security ---
            ['title' => 'Digital Security Awareness', 'description' => 'Learn about types of security threats, social engineering, identity theft, and data classification. Develop awareness to protect yourself and your organization from cyber threats.', 'url' => 'https://alison.com/course/digital-security-awareness', 'level' => 'beginner', 'title_bm' => 'Kesedaran Keselamatan Digital', 'description_bm' => 'Pelajari tentang jenis ancaman keselamatan, kejuruteraan sosial, pencurian identiti, dan pengelasan data. Kembangkan kesedaran untuk melindungi diri dan organisasi anda.', 'image' => 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80'],
            ['title' => 'Data Protection and Privacy Compliance', 'description' => 'Understand the General Data Protection Regulation (GDPR) and data protection principles. Learn about lawful data processing, individual rights, and organizational compliance obligations.', 'url' => 'https://alison.com/course/gdpr-data-protection', 'level' => 'intermediate', 'title_bm' => 'Perlindungan Data dan Pematuhan Privasi', 'description_bm' => 'Fahami Peraturan Perlindungan Data Umum (GDPR) dan prinsip perlindungan data. Pelajari tentang pemprosesan data yang sah dan hak individu.', 'image' => 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80'],
            ['title' => 'Cybersecurity Risk Management', 'description' => 'Learn to identify, assess, and manage cybersecurity risks in organizational environments. Covers risk frameworks, threat modeling, incident response planning, and security governance.', 'url' => 'https://www.coursera.org/learn/cybersecurity-risk-management', 'level' => 'advanced', 'title_bm' => 'Pengurusan Risiko Keselamatan Siber', 'description_bm' => 'Pelajari cara mengenal pasti, menilai, dan mengurus risiko keselamatan siber dalam persekitaran organisasi. Merangkumi rangka kerja risiko dan perancangan tindak balas insiden.', 'image' => 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80'],

            // --- C6 – Professional Development & Engagement ---
            ['title' => 'Continuous Learning in the Digital Workplace', 'description' => 'Develop strategies for lifelong learning and professional growth in the digital era. Learn to set learning goals, use online platforms effectively, and build a digital professional portfolio.', 'url' => 'https://learn.microsoft.com/en-us/training/', 'level' => 'beginner', 'title_bm' => 'Pembelajaran Berterusan di Tempat Kerja Digital', 'description_bm' => 'Kembangkan strategi untuk pembelajaran seumur hidup dan pertumbuhan profesional dalam era digital.', 'image' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80'],
            ['title' => 'Digital Leadership and Change Management', 'description' => 'Learn to lead digital transformation initiatives, manage organizational change, and drive technology adoption. Covers leadership strategies for digital innovation and change resistance.', 'url' => 'https://www.coursera.org/learn/digital-transformation', 'level' => 'intermediate', 'title_bm' => 'Kepimpinan Digital dan Pengurusan Perubahan', 'description_bm' => 'Pelajari cara memimpin inisiatif transformasi digital, mengurus perubahan organisasi, dan memacu penggunaan teknologi.', 'image' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80'],
            ['title' => 'Innovation Management', 'description' => 'Master the principles of managing innovation within organizations. Learn innovation frameworks, how to foster creative cultures, manage innovation pipelines, and measure innovation outcomes.', 'url' => 'https://www.coursera.org/learn/innovation-management', 'level' => 'advanced', 'title_bm' => 'Pengurusan Inovasi', 'description_bm' => 'Kuasai prinsip pengurusan inovasi dalam organisasi. Pelajari rangka kerja inovasi, cara memupuk budaya kreatif, dan mengukur hasil inovasi.', 'image' => 'https://images.unsplash.com/photo-1451186859696-371d9477be93?w=800&q=80'],

            // --- C7 – Digital Transformation & Governance ---
            ['title' => 'AI Fluency', 'description' => 'Understand the fundamentals of Artificial Intelligence, how AI creates new content, and how it transforms internet search. Learn to use AI responsibly and explore its role in making the world more accessible.', 'url' => 'https://rakyatdigital.gov.my/', 'level' => 'beginner', 'title_bm' => 'Kecakapan AI', 'description_bm' => 'Fahami asas Kecerdasan Buatan, bagaimana AI mencipta kandungan baharu, dan bagaimana ia mengubah cara carian internet. Belajar menggunakan AI secara bertanggungjawab.', 'image' => 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80'],
            ['title' => 'Generative AI Fundamentals', 'description' => 'Explore the core concepts, techniques, and applications of generative AI. Learn how generative AI creates original content from text and images to music and code in real-world scenarios.', 'url' => 'https://rakyatdigital.gov.my/', 'level' => 'intermediate', 'title_bm' => 'Asas AI Generatif', 'description_bm' => 'Teroka konsep teras, teknik, dan aplikasi AI generatif. Pelajari bagaimana AI generatif mencipta kandungan asal daripada teks dan imej kepada muzik dan kod.', 'image' => 'https://images.unsplash.com/photo-1684369175833-4b445ad6bfb5?w=800&q=80'],
            ['title' => 'Digital Transformation Strategy', 'description' => 'Develop comprehensive digital transformation strategies for organizations. Learn to assess digital maturity, design transformation roadmaps, and align technology initiatives with business objectives.', 'url' => 'https://www.coursera.org/learn/digital-transformation-strategy', 'level' => 'advanced', 'title_bm' => 'Strategi Transformasi Digital', 'description_bm' => 'Kembangkan strategi transformasi digital yang komprehensif untuk organisasi. Pelajari cara menilai kematangan digital dan mereka bentuk peta jalan transformasi.', 'image' => 'https://images.unsplash.com/photo-1451186859696-371d9477be93?w=800&q=80'],

            // --- C8 – Digital Creation & Innovation ---
            ['title' => 'Digital Content Creation', 'description' => 'Learn to create engaging digital content including documents, presentations, and social media graphics. Master tools and techniques for effective visual communication in the workplace.', 'url' => 'https://learn.microsoft.com/en-us/training/', 'level' => 'beginner', 'title_bm' => 'Penciptaan Kandungan Digital', 'description_bm' => 'Pelajari cara mencipta kandungan digital yang menarik termasuk dokumen, persembahan, dan grafik media sosial.', 'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80'],
            ['title' => 'Digital Media Production for Government Communications', 'description' => 'Learn video production and digital storytelling techniques for government communications. Covers video editing, visual composition, and creating engaging multimedia content for public outreach.', 'url' => 'https://alison.com/course/digital-photography', 'level' => 'intermediate', 'title_bm' => 'Pengeluaran Media Digital untuk Komunikasi Kerajaan', 'description_bm' => 'Pelajari teknik pengeluaran video dan penceritaan digital untuk komunikasi kerajaan. Merangkumi penyuntingan video dan komposisi visual.', 'image' => 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80'],
            ['title' => 'UX Design Foundations', 'description' => 'Learn the fundamentals of User Experience (UX) design including user research, wireframing, prototyping, and usability testing. Apply UX principles to create user-centered digital services.', 'url' => 'https://www.coursera.org/learn/ux-design', 'level' => 'advanced', 'title_bm' => 'Asas Reka Bentuk UX', 'description_bm' => 'Pelajari asas reka bentuk Pengalaman Pengguna (UX) termasuk penyelidikan pengguna, pemetaan wayar, prototaip, dan ujian kebolehgunaan.', 'image' => 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=800&q=80'],

            // --- C9 – Digital Ethics & Inclusion ---
            ['title' => 'AI Governance and Ethics', 'description' => 'Explore the key laws, frameworks, and procedures that govern AI, while addressing the ethical challenges crucial for building reliable and trustworthy AI systems.', 'url' => 'https://alison.com/course/ai-governance-and-ethics', 'level' => 'beginner', 'title_bm' => 'Tadbir Urus dan Etika AI', 'description_bm' => 'Teroka undang-undang, rangka kerja, dan prosedur utama yang mentadbir AI, sambil menangani cabaran etika yang penting untuk membina sistem AI yang boleh dipercayai.', 'image' => 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80'],
            ['title' => 'AI Safety and Responsible Use', 'description' => 'Learn about AI ethics, misinformation risks, deepfakes, and ethical AI practices. Understand how to use, manage, and develop AI technology safely and responsibly.', 'url' => 'https://rakyatdigital.gov.my/', 'level' => 'intermediate', 'title_bm' => 'Keselamatan AI dan Penggunaan Bertanggungjawab', 'description_bm' => 'Pelajari tentang etika AI, risiko maklumat palsu, deepfake, dan amalan AI beretika. Fahami cara menggunakan dan membangunkan teknologi AI dengan selamat.', 'image' => 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80'],
            ['title' => 'Digital Accessibility and Inclusive Design', 'description' => 'Learn to design digital content and services that are accessible to all users, including those with disabilities. Covers WCAG standards, assistive technologies, and inclusive design principles.', 'url' => 'https://www.coursera.org/learn/web-accessibility', 'level' => 'advanced', 'title_bm' => 'Kebolehcapaian Digital dan Reka Bentuk Inklusif', 'description_bm' => 'Pelajari cara mereka bentuk kandungan dan perkhidmatan digital yang boleh diakses oleh semua pengguna, termasuk mereka yang mempunyai kecacatan.', 'image' => 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=800&q=80'],

            // --- C10 – Functional Skills & Applications ---
            ['title' => 'Project Management Fundamentals', 'description' => 'Learn the core principles of project management including planning, scheduling, risk management, and stakeholder communication. Apply project management tools to organize work effectively.', 'url' => 'https://alison.com/course/project-management', 'level' => 'beginner', 'title_bm' => 'Asas Pengurusan Projek', 'description_bm' => 'Pelajari prinsip teras pengurusan projek termasuk perancangan, penjadualan, pengurusan risiko, dan komunikasi pihak berkepentingan.', 'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80'],
            ['title' => 'Microsoft 365 for Government Productivity', 'description' => 'Master Microsoft 365 tools for government productivity including Outlook, SharePoint, OneDrive, and Planner. Learn to integrate these tools for efficient government workflows.', 'url' => 'https://learn.microsoft.com/en-us/training/', 'level' => 'intermediate', 'title_bm' => 'Microsoft 365 untuk Produktiviti Kerajaan', 'description_bm' => 'Kuasai alat Microsoft 365 untuk produktiviti kerajaan termasuk Outlook, SharePoint, OneDrive, dan Planner.', 'image' => 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80'],
            ['title' => 'Data Analysis and Visualization with Power BI', 'description' => 'Learn to create interactive dashboards and data visualizations using Power BI. Connect to data sources, transform data, build reports, and share insights for data-driven decision making.', 'url' => 'https://learn.microsoft.com/en-us/training/power-bi/', 'level' => 'advanced', 'title_bm' => 'Analisis Data dan Visualisasi dengan Power BI', 'description_bm' => 'Pelajari cara mencipta papan pemuka interaktif dan visualisasi data menggunakan Power BI. Sambung ke sumber data, transformasi data, dan bina laporan.', 'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80'],
        ];

        foreach ($courses as $course) {
            Course::firstOrCreate(
                ['title' => $course['title']],
                array_merge($course, ['created_by' => $trainer?->id ?? 1])
            );
        }

        // Seed course enrollments
        $allCourses = Course::pluck('id')->toArray();
        $staffEmails = ['staff01@test.com', 'ahmad@test.com', 'siti@test.com', 'raj@test.com', 'meiling@test.com', 'farah@test.com', 'weiming@test.com'];

        $enrollments = [
            // staff01 - active in several courses across categories
            ['staff01@test.com', [0 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-07-15'], 1 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-07-20'], 2 => ['progress' => 65.5, 'status' => 'active'], 4 => ['progress' => 30.0, 'status' => 'active'], 8 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-08-10'], 14 => ['progress' => 60.0, 'status' => 'active'], 22 => ['progress' => 40.0, 'status' => 'active'], 29 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-09-15']]],
            // ahmad - mix of completed and active
            ['ahmad@test.com', [0 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-06-10'], 3 => ['progress' => 45.0, 'status' => 'active'], 5 => ['progress' => 80.0, 'status' => 'active'], 11 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-07-05'], 17 => ['progress' => 70.0, 'status' => 'active'], 26 => ['progress' => 55.0, 'status' => 'active']]],
            // siti - mostly completed across many categories
            ['siti@test.com', [0 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-05-20'], 1 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-06-01'], 2 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-06-15'], 6 => ['progress' => 55.0, 'status' => 'active'], 9 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-07-20'], 13 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-08-05'], 20 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-08-20'], 32 => ['progress' => 80.0, 'status' => 'active']]],
            // raj - mixed across C3-C6
            ['raj@test.com', [1 => ['progress' => 90.0, 'status' => 'active'], 3 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-08-01'], 7 => ['progress' => 25.0, 'status' => 'active'], 12 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-08-15'], 15 => ['progress' => 50.0, 'status' => 'active'], 23 => ['progress' => 35.0, 'status' => 'active']]],
            // meiling - just started, spread across categories
            ['meiling@test.com', [0 => ['progress' => 10.0, 'status' => 'active'], 2 => ['progress' => 5.0, 'status' => 'active'], 4 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-09-01'], 10 => ['progress' => 30.0, 'status' => 'active'], 18 => ['progress' => 15.0, 'status' => 'active'], 27 => ['progress' => 20.0, 'status' => 'active']]],
            // farah - advanced learner, many completed
            ['farah@test.com', [0 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-04-10'], 1 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-05-05'], 2 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-06-01'], 5 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-07-01'], 6 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-08-01'], 7 => ['progress' => 75.0, 'status' => 'active'], 9 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-08-10'], 14 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-09-01'], 19 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-09-10'], 21 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-09-15'], 24 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-09-20'], 30 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-09-25'], 33 => ['progress' => 90.0, 'status' => 'active']]],
            // weiming - moderate activity
            ['weiming@test.com', [0 => ['progress' => 50.0, 'status' => 'active'], 3 => ['progress' => 20.0, 'status' => 'active'], 8 => ['progress' => 100, 'status' => 'completed', 'completed_at' => '2025-09-05'], 16 => ['progress' => 60.0, 'status' => 'active'], 25 => ['progress' => 45.0, 'status' => 'active'], 31 => ['progress' => 10.0, 'status' => 'active']]],
        ];

        foreach ($enrollments as [$email, $courseEnrollments]) {
            $user = User::where('email', $email)->first();
            if (!$user) continue;

            foreach ($courseEnrollments as $courseIdx => $enrollData) {
                if (!isset($allCourses[$courseIdx])) continue;

                UserCourse::firstOrCreate(
                    ['user_id' => $user->id, 'course_id' => $allCourses[$courseIdx]],
                    array_merge([
                        'started_at' => now()->subMonths(3),
                        'progress' => $enrollData['progress'],
                        'status' => $enrollData['status'],
                        'completed_at' => $enrollData['completed_at'] ?? null,
                    ])
                );
            }
        }
    }
}
